version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current
permissions:
  - object: /var/app/current
    pattern: "**"
    owner: webapp
    group: webapp
    mode: 755
hooks:
  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root
